In [3]:
import numpy as np
from initialisation import *

In [4]:
N = 5
M = 10

In [5]:
vin = np.ones((N, M))
mass = np.array([1, 2, 3, 4, 5])

In [6]:
vin

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
mass.reshape(5,1).T

array([[1, 2, 3, 4, 5]])

In [8]:
vin * mass[:, None]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [9]:
from size_scaled_func import *

In [10]:
a = scale_vin(vin, mass, 0.5, -0.25)

In [11]:
a

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821,
        0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821],
       [0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784,
        0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784],
       [0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339,
        0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339],
       [0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015,
        0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015]])

In [23]:
int_C(N, 2)

array([[2.68795064],
       [1.03459088],
       [2.78688018],
       [3.40661926],
       [1.34377559]])