In [1]:
import numpy as np
from initialisation import *

In [2]:
N = 5
M = 10

In [3]:
vin = np.ones((N, M))
mass = np.array([1, 2, 3, 4, 5])

In [4]:
vin

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
mass.reshape(5,1).T

array([[1, 2, 3, 4, 5]])

In [6]:
vin * mass[:, None]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [7]:
from size_scaled_func import *

In [8]:
a = scale_vin(vin, mass, 0.5, -0.25)

In [9]:
a

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821,
        0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821],
       [0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784,
        0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784],
       [0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339,
        0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339],
       [0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015,
        0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015]])

In [10]:
int_C(N, 2)

TypeError: int_C() missing 1 required positional argument: 'assemblenum'

In [ ]:
int_R(M, 30)

array([[21.25117263],
       [31.71340202],
       [35.76517901],
       [28.73781982],
       [34.90660393],
       [32.57109421],
       [31.10589835],
       [24.64978335],
       [29.05252085],
       [31.27500722]])

In [ ]:
int_preferences(N, M, 0.1, 0.001)

[[0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]]


array([[0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 ,
        0.9187462 , 0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 ],
       [0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 ,
        0.91864359, 0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 ],
       [0.00920952, 0.00920952, 0.00920952, 0.00920952, 0.00920952,
        0.00920952, 0.00920952, 0.00920952, 0.91711428, 0.00920952],
       [0.0090262 , 0.0090262 , 0.0090262 , 0.0090262 , 0.0090262 ,
        0.0090262 , 0.0090262 , 0.0090262 , 0.91876423, 0.0090262 ],
       [0.00917006, 0.00917006, 0.00917006, 0.00917006, 0.00917006,
        0.00917006, 0.00917006, 0.91746948, 0.00917006, 0.00917006]])

In [ ]:
D = np.array(
    [
    [1, 2, 3, 4, 5], 
    [2, 3, 4, 5, 6]
    ]
)
sum = np.sum(D, axis=0)

In [ ]:
D/sum[np.newaxis, :]

array([[0.33333333, 0.4       , 0.42857143, 0.44444444, 0.45454545],
       [0.66666667, 0.6       , 0.57142857, 0.55555556, 0.54545455]])

In [ ]:
sum

array([ 3,  5,  7,  9, 11])

In [ ]:
D[0, :]/sum[0]

array([0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333])

In [ ]:
N = 5
M = 10

In [ ]:
p = np.ones((N, M))
R = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]).reshape(10, 1)

In [ ]:
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
R

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
d = p* R.T[:, np.newaxis]

In [ ]:
d = d.reshape(5, 10)

In [ ]:
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
d.shape

(5, 10)

In [ ]:
vmax = np.ones((N, M))*2

In [ ]:
vmax

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [ ]:
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
d[d>8]

array([ 9., 10.,  9., 10.,  9., 10.,  9., 10.,  9., 10.])

In [11]:
p = int_preferences(N, M, 0.1, 0.01, 1)
vmax = int_vmax(N, M, 30, p, 1)

In [12]:
p

array([[0.05214742, 0.05214742, 0.05214742, 0.05214742, 0.05214742,
        0.53067325, 0.05214742, 0.05214742, 0.05214742, 0.05214742],
       [0.05218544, 0.05218544, 0.05218544, 0.05218544, 0.05218544,
        0.53033108, 0.05218544, 0.05218544, 0.05218544, 0.05218544],
       [0.05261758, 0.05261758, 0.05261758, 0.05261758, 0.05261758,
        0.05261758, 0.05261758, 0.52644181, 0.05261758, 0.05261758],
       [0.05263127, 0.05263127, 0.05263127, 0.05263127, 0.05263127,
        0.52631855, 0.05263127, 0.05263127, 0.05263127, 0.05263127],
       [0.05259616, 0.05259616, 0.05259616, 0.05259616, 0.05259616,
        0.52663456, 0.05259616, 0.05259616, 0.05259616, 0.05259616]])

In [13]:
np.sum(p[1, :])

0.9999999999999998