In [1]:
import numpy as np
from initialisation import *

In [2]:
N = 5
M = 10

In [3]:
vin = np.ones((N, M))
mass = np.array([1, 2, 3, 4, 5])

In [4]:
vin

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
mass.reshape(5,1).T

array([[1, 2, 3, 4, 5]])

In [6]:
vin * mass[:, None]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [7]:
from size_scaled_func import *

In [8]:
a = scale_vin(vin, mass, 0.5, -0.25)

In [9]:
a

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821,
        0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821],
       [0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784,
        0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784],
       [0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339,
        0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339],
       [0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015,
        0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015]])

In [10]:
int_C(N, 2, 1)

array([[2.41623971],
       [2.49807721],
       [1.40739959],
       [1.75730828],
       [1.32119437]])

In [11]:
int_R(M, 30,1)

array([[43.5342492 ],
       [33.14066354],
       [34.53984723],
       [32.51912877],
       [33.25558974],
       [28.40340978],
       [25.75961508],
       [33.02982675],
       [19.90915878],
       [33.70061029]])

In [12]:
D = np.array(
    [
    [1, 2, 3, 4, 5], 
    [2, 3, 4, 5, 6]
    ]
)
sum = np.sum(D, axis=0)

In [13]:
D/sum[np.newaxis, :]

array([[0.33333333, 0.4       , 0.42857143, 0.44444444, 0.45454545],
       [0.66666667, 0.6       , 0.57142857, 0.55555556, 0.54545455]])

In [14]:
sum

array([ 3,  5,  7,  9, 11])

In [15]:
D[0, :]/sum[0]

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [16]:
N = 5
M = 10

In [17]:
p = np.ones((N, M))
R = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]).reshape(10, 1)

In [18]:
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
R

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [33]:
d = p* R.T[:, np.newaxis]

In [21]:
d = d.reshape(5, 10)

In [22]:
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [23]:
d.shape

(5, 10)

In [24]:
vmax = np.ones((N, M))*2

In [25]:
vmax

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [26]:
d

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [27]:
d[d>8]

array([ 9., 10.,  9., 10.,  9., 10.,  9., 10.,  9., 10.])

In [28]:
p, number = int_preferences(N, M, 0.1, 1)
vmax = int_vmax(N, M, 30, p, number, 1)

In [29]:
number

1

In [30]:
p

array([[0.00915949, 0.00915949, 0.00915949, 0.00915949, 0.00915949,
        0.91756461, 0.00915949, 0.00915949, 0.00915949, 0.00915949],
       [0.00916066, 0.00916066, 0.00916066, 0.00916066, 0.00916066,
        0.91755406, 0.00916066, 0.00916066, 0.00916066, 0.00916066],
       [0.00917389, 0.00917389, 0.00917389, 0.00917389, 0.00917389,
        0.00917389, 0.00917389, 0.91743502, 0.00917389, 0.00917389],
       [0.0091743 , 0.0091743 , 0.0091743 , 0.0091743 , 0.0091743 ,
        0.91743128, 0.0091743 , 0.0091743 , 0.0091743 , 0.0091743 ],
       [0.00917324, 0.00917324, 0.00917324, 0.00917324, 0.00917324,
        0.91744088, 0.00917324, 0.00917324, 0.00917324, 0.00917324]])

In [32]:
vmax

array([[ 0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        29.59393152,  0.1       ,  0.1       ,  0.1       ,  0.1       ],
       [ 0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        30.74507123,  0.1       ,  0.1       ,  0.1       ,  0.1       ],
       [ 0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
         0.1       ,  0.1       , 30.38609989,  0.1       ,  0.1       ],
       [ 0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        28.87407792,  0.1       ,  0.1       ,  0.1       ,  0.1       ],
       [ 0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        30.03956216,  0.1       ,  0.1       ,  0.1       ,  0.1       ]])