In [2]:
import numpy as np
from initialisation import *

In [3]:
N = 5
M = 10

In [4]:
vin = np.ones((N, M))
mass = np.array([1, 2, 3, 4, 5])

In [5]:
vin

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
mass.reshape(5,1).T

array([[1, 2, 3, 4, 5]])

In [7]:
vin * mass[:, None]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [8]:
from size_scaled_func import *

In [9]:
a = scale_vin(vin, mass, 0.5, -0.25)

In [10]:
a

array([[0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821,
        0.42044821, 0.42044821, 0.42044821, 0.42044821, 0.42044821],
       [0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784,
        0.37991784, 0.37991784, 0.37991784, 0.37991784, 0.37991784],
       [0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339,
        0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339],
       [0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015,
        0.33437015, 0.33437015, 0.33437015, 0.33437015, 0.33437015]])

In [11]:
int_C(N, 2)

array([[2.68795064],
       [1.03459088],
       [2.78688018],
       [3.40661926],
       [1.34377559]])

In [12]:
int_R(M, 30)

array([[21.25117263],
       [31.71340202],
       [35.76517901],
       [28.73781982],
       [34.90660393],
       [32.57109421],
       [31.10589835],
       [24.64978335],
       [29.05252085],
       [31.27500722]])

In [13]:
int_preferences(N, M, 0.1, 0.001)

[[0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]
 [0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001]]


array([[0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 ,
        0.9187462 , 0.0090282 , 0.0090282 , 0.0090282 , 0.0090282 ],
       [0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 ,
        0.91864359, 0.0090396 , 0.0090396 , 0.0090396 , 0.0090396 ],
       [0.00920952, 0.00920952, 0.00920952, 0.00920952, 0.00920952,
        0.00920952, 0.00920952, 0.00920952, 0.91711428, 0.00920952],
       [0.0090262 , 0.0090262 , 0.0090262 , 0.0090262 , 0.0090262 ,
        0.0090262 , 0.0090262 , 0.0090262 , 0.91876423, 0.0090262 ],
       [0.00917006, 0.00917006, 0.00917006, 0.00917006, 0.00917006,
        0.00917006, 0.00917006, 0.91746948, 0.00917006, 0.00917006]])

In [27]:
D = np.array(
    [
    [1, 2, 3, 4, 5], 
    [2, 3, 4, 5, 6]
    ]
)
sum = np.sum(D, axis=0)

In [29]:
D/sum[np.newaxis, :]

array([[0.33333333, 0.4       , 0.42857143, 0.44444444, 0.45454545],
       [0.66666667, 0.6       , 0.57142857, 0.55555556, 0.54545455]])

In [30]:
sum

array([ 3,  5,  7,  9, 11])

In [26]:
D[0, :]/sum[0]

array([0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333])